//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Configurely.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeData
    {
        public int EmployeeID { get; set; }
        public int FieldID { get; set; }
        public string Value { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Field Field { get; set; }
    }
}
